Add new ASR rule: "Block abuse of exploited vulnerable signed drivers"
0x6d69636b/windows_hardening pull request #38
Opened 2021-05-29 09:18 UTC by Harvester57

Hi,

I stumbled upon a Twitter post (https://twitter.com/JimSycurity/status/1395821588252143617), mentioning a new ASR rule, recently added by Microsoft:

https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction?view=o365-worldwide#block-abuse-of-exploited-vulnerable-signed-drivers

> This rule prevents an application from writing a vulnerable, signed driver to disk. In-the-wild, vulnerable signed drivers can be > exploited by local applications - that have sufficient privileges - to gain access to the kernel. Vulnerable signed drivers enable > attackers to disable or circumvent security solutions, eventually leading to system compromise.

> This rule does not block a driver already existing on the system from being loaded.

Did I assign the two IDs correctly ? I just continued the numeration for the ASR section, but it kind of break the current logic (IDs 1901-1915 for registry keys, and 1916-1930 for MpPreferenceAsr)

2021-05-29 11:57 UTC, 0x6d69636b requested changes
Could you please the ID's 1931 and 1932, there are the next free ones. I don't have a particular order for Registry and MpPreferenceAsr, first I had only registry checks, and therefore the IDs were assigned that way. And could you please move the two rows up under ID 1930?

2021-05-29 11:58 UTC, 0x6d69636b commented
Thank you for this pull request :-) There is still some renumbering and moving to be done, but that shouldn't be a big deal. ;-)

2021-05-30 17:55 UTC, Harvester57 commented
Sorry for the delay, I changed the IDs and moved the two lines under ID 1930 :)

2021-05-30 17:55 UTC, 0x6d69636b approved these changes

2021-05-30 17:55 UTC, merged