Update to send any information to Microsoft
0x6d69636b/windows_hardening pull request #43
Opened 2021-06-18 08:51 UTC by ataumo

[I propose to send any information to Microsoft]
------------------------------------------------
->Update : RecommendedValue value of 1745
          (3 -> 0)

"This policy setting allows you to control what information is shared with Bing in Search."

(0)Disable
(1)User info and location
(2)User info only
(3)Anonymous info
------------------------------------------------
->Update : RecommendedValue value of 1802
          (2 -> 0)

"Specifies the type of membership in Microsoft Active Protection Service. 
Microsoft Active Protection Service is an online community that helps you choose how to respond to potential threats. 
The community also helps prevent the spread of new malicious software."

(0)Disable
(1)Basic
(2)Advanced

Disabled : Send no information to Microsoft. This is the default value.
Basic membership : Send basic information to Microsoft about detected software, including where the software came from, the actions that you apply or that apply automatically, and whether the actions succeeded.
Advanced membership : In addition to basic information, send more information to Microsoft about malicious software, spyware, and potentially unwanted software, including the location of the software, file names, how the software operates, and how it affects your computer.
------------------------------------------------
->Update : RecommendedValue value of 1803
          (0 -> 2)

"Specifies how Windows Defender checks for user consent for certain samples."

(0)AlwaysPrompt
(1)SendSafeSamples
(2)NeverSend
(3)SendAllSamples

2021-06-19 06:34 UTC, 0x6d69636b requested changes
Thank you for your effort :+1: 

ID 1745: If this policy setting is set to disabled, than the user can choose what information is shared, but sadly we can't disable this completely. Therefore setting it to disable has no advantage.

ID 1802: Microsoft connected the MAPS membership with their cloud-delivered protection. If one disables MAPS, then you can't use the cloud-delivered protection anymore. I notice significantly better detection results for Defender, for example PowerShell based malware is detected with AMSI when this is enabled and not if inactive. Therefore my tradeoff here is to choose better detection results over privacy. Sadly I can't have both. :( 

ID 1803: This is correct, my value is false.

Therefore, could you please remove ID 1745 and 1802?

2021-06-21 17:39 UTC, ataumo commented
Okay ! I agree with your point of view.
I have just applied the requested changes ;)

2021-06-21 17:54 UTC, 0x6d69636b approved these changes

2021-06-21 17:55 UTC, 0x6d69636b commented
Looks good :) Merci beaucoup

2021-06-21 17:55 UTC, merged