Simplifying code structure and cleaning script
0x6d69636b/windows_hardening pull request #86
Opened 2022-03-25 09:22 UTC by An78toi13ne06

2022-03-26 06:55 UTC, 0x6d69636b requested changes
Thank you very much for your tremendous work! :heart_eyes_cat: 
I added a few comments, please resolve them and after that I'll merge it

2022-03-26 06:55 UTC, 0x6d69636b commented on Invoke-HardeningKitty.ps1
> +            [Int]
The CIS benchmark list for example has an ID like _18.9.108.4.2.2_, therefore we should use `[String]` for the ID as well

2022-03-26 06:55 UTC, 0x6d69636b commented on Invoke-HardeningKitty.ps1
> +    $script:StatsError = 0
Could you use a capital letter for the `$Script` variable, please?

2022-03-26 06:55 UTC, 0x6d69636b commented on Invoke-HardeningKitty.ps1
> +            [Int]
Again, we should use `[String]` for the ID

2022-03-26 06:55 UTC, 0x6d69636b commented on Invoke-HardeningKitty.ps1
> +                    $StatsError++
This should be changed to $Script:StatsError as well

2022-03-26 06:55 UTC, 0x6d69636b commented on Invoke-HardeningKitty.ps1
> +        If ($StatsError -gt 0) {
Here we should replace the variable to $Script:StatsError as well, and in the output below

2022-03-27 13:26 UTC, An78toi13ne06 commented
Changes made ^^
Don't know how to show it with github but each change asked has been resolved.

2022-03-27 14:38 UTC, 0x6d69636b commented
I guess you just can click on the "Resolve conversation" button. But it doesn't matter if you changed it anyway ;-)

2022-03-27 14:49 UTC, merged